version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - 80:80
      - 8080:8080
      - 3000:3000
    env_file:
      - ./frontend/src/.env.local
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    working_dir: /app

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - 5000:5000
    env_file:
      - ./backend/kokutou/.env.local
    volumes:
      - ./backend:/app
    working_dir: /app

  migration:
    image: flyway/flyway
    volumes:
      - ./db/migration/schema:/flyway/sql
    depends_on:
      - db

  db:
    build:
      context: ./db
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  node_modules:
  mysqldata:
