version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    command: yarn run dev
    container_name: frontend

    # ポートマッピング。これがないとブラウザと通信できなかったりcurlできなかったりする。
    ports:
      - 80:80
      - 8080:8080
      - 3000:3000
    env_file:
      - ./frontend/.dev.env
    # ローカルとコンテナのボリュームを同期
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    working_dir: /app

  backend:
    build:
      context: ./backend
    command: python3 run.py
    container_name: backend
    ports:
      - 5000
    env_file:
      - ./backend/.dev.env
    volumes:
      - ./backend:/app
    working_dir: /app

volumes:
  node_modules: