swagger: '2.0'
info:
  version: '1.0'
  title: Kokutou
  description: Experiment system
  contact:
    name: kudolab
host: 'localhost:5000'
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /subjects:
    get:
      description: 被験者一覧取得
      summary: index-subject
      tags:
        - Subject
      operationId: index-subject
      deprecated: false
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ListSubject'
          headers: {}
    post:
      description: 被験者作成
      summary: create-subject
      tags:
        - Subject
      operationId: create-subject
      deprecated: false
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          description: '被験者詳細'
          schema:
            $ref: '#/definitions/CreateSubjectRequest'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/CreateSubjectResponse'
          headers: {}
  '/subjects/{subject_id}':
    get:
      description: 被験者詳細
      summary: show-subject
      tags:
        - Subject
      operationId: show-subject
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: subject_id
          in: path
          required: true
          type: integer
          format: int64
          description: subject id
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Subject'
          headers: {}
    parameters:
      - type: integer
        name: subject_id
        in: path
        required: true
definitions:
  CreateSubjectRequest:
    title: CreateSubject
    type: object
    properties:
      name:
        type: string
      system_name:
        type: string
    required:
      - name
      - system_name
  ListSubject:
    title: IndexSubject
    type: object
    properties:
      subjects:
        type: array
        items:
          $ref: '#/definitions/Subject'
  Subject:
    title: ShowSubjectResponse
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      system_name:
        type: string
    required:
      - id
      - name
      - system_name
  CreateSubjectResponse:
    title: CreateSubjectResponse
    type: object
    properties:
      id:
        type: integer
        format: int64
    required:
      - id
tags:
  - name: Subject
responses: {}
