AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for kokutou-questplus

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  KokutouQuestPlusFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Events:
        KokutouQuestPlus:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /width/next_stim
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./kokutou_questplus
      DockerTag: python3.8-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  KokutouQuestPlusApi:
    Description: "API Gateway endpoint URL for Prod stage for Kokutou QuestPlus function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/next_stim/"
  KokutouQuestPlusFunction:
    Description: "Kokutou QuestPlus Lambda Function ARN"
    Value: !GetAtt KokutouQuestPlusFunction.Arn
  KokutouQuestPlusFunctionIamRole:
    Description: "Implicit IAM Role created for Kokutou QuestPlus function"
    Value: !GetAtt KokutouQuestPlusFunctionRole.Arn
