steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/kokutou-47c17/kokutou', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/kokutou-47c17/kokutou']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'kokutou', '--image', 'gcr.io/kokutou-47c17/kokutou', '--region', 'northeast-1']
images:
- gcr.io/kokutou-47c17/kokutou
