steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-docker-image'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-docker-image'
  args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'deploy-cloud-run'
  args:
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME}'
    - '--image'
    - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
    - '--region'
    - '${_REGION}'
substitutions:
  _REGION: asia-northeast1 # tokyo
  _SERVICE_NAME: kokutou # service name
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'