import Head from "next/head";
import Link from "next/link";
import styles from "../../styles/Home.module.css";
import React from "react";
import { subjectClient } from "../api";

export default function ListSubjects() {
  const [subjects, setSubjects] = React.useState<Array<Subject>>([]);
  const [loading, setLoading] = React.useState<boolean>(false);

  React.useState(() => {
    setLoading(true);
    subjectClient
      .getSubjects()
      .then(setSubjects)
      .catch((e) => {
        console.dir(e, { depth: null });
      })
      .finally(() => setLoading(false));
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>kokutou</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>黒糖</h1>
        <p className={styles.description}>被験者選択ページ</p>

        {!loading && (
          <div className={styles.grid}>
            {subjects.map((subject) => (
              <Link href={`/subject/${subject.id}/experiment`} key={subject.id} passHref>
                <div className={styles.card}>
                  <h2>{subject.name} &rarr;</h2>
                </div>
              </Link>
            ))}
          </div>
        )}
      </main>

      <footer className={styles.footer}>Powered by {"kudolab"}</footer>
    </div>
  );
}

// function ListSubject({ subjects }) {}

// function get() {}
