import Head from "next/head"
import Link from "next/link"
import Image from "next/image"
import styles from "../../styles/Home.module.css"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>kokutou</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>黒糖</h1>
        <p className={styles.description}>被験者選択ページ</p>

        <div className={styles.grid}>
          <Link href="/subject/:subjectId/experiment" passHref>
            <div className={styles.card}>
              <h2>被験者名 &rarr;</h2>
            </div>
          </Link>
                         <Link href="/subject/:subjectId/experiment" passHref>
            <div className={styles.card}>
              <h2>被験者名 &rarr;</h2>
            </div>
          </Link>
          <Link href="/subject/:subjectId/experiment" passHref>
            <div className={styles.card}>
              <h2>被験者名 &rarr;</h2>
            </div>
          </Link>
          <Link href="/subject/:subjectId/experiment" passHref>
            <div className={styles.card}>
              <h2>被験者名 &rarr;</h2>
            </div>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>Powered by {"kudolab"}</footer>
    </div>
  )
}
